import Intents
import Foundation

// Note: This will be generated by Xcode when you create the Intent Definition
// After creating the Intent Definition file, Xcode will auto-generate:
// - GetNextHarvesterEventIntent and GetNextHarvesterEventIntentResponse
// - GetAllHarvesterTimesIntent and GetAllHarvesterTimesIntentResponse

@objc(IntentHandler)
public class IntentHandler: INExtension, GetNextHarvesterEventIntentHandling {
    
    public override init() {
        super.init()
        print("✅ IntentHandler initialized")
    }
    
    // Override handler(for:) to route intents to self
    public override func handler(for intent: INIntent) -> Any? {
        print("🔵 IntentHandler.handler(for:) called with intent: \(intent)")
        if intent is GetNextHarvesterEventIntent {
            return self
        }
        return nil
    }
    
    // Handle "when is the next harvester event"
    public func handle(intent: GetNextHarvesterEventIntent, completion: @escaping (GetNextHarvesterEventIntentResponse) -> Void) {
        print("🔵 IntentHandler.handle() called!")
        print("   Intent: \(intent)")
        
        Task {
            print("   Starting API call...")
            let apiService = HarvesterAPIService()
            
            do {
                let events = try await apiService.fetchHarvesterEvents()
                print("   ✅ Got \(events.count) events")
                
                if let event = events.first {
                    print("   📅 Next event: \(event.startTime) - \(event.endTime)")
                    let response = GetNextHarvesterEventIntentResponse(code: .success, userActivity: nil)
                    response.eventTime = "\(event.startTime) - \(event.endTime)"
                    response.timeUntil = event.isCurrent ? "Ends in \(event.timeUntil)" : "Starts in \(event.timeUntil)"
                    response.maps = event.maps.joined(separator: ", ")
                    print("   ✅ Response: \(response.eventTime ?? "nil"), \(response.timeUntil ?? "nil"), \(response.maps ?? "nil")")
                    completion(response)
                } else {
                    print("   ⚠️ No events found")
                    let response = GetNextHarvesterEventIntentResponse(code: .failure, userActivity: nil)
                    response.eventTime = "No upcoming events"
                    completion(response)
                }
            } catch {
                print("   ❌ Error: \(error.localizedDescription)")
                let response = GetNextHarvesterEventIntentResponse(code: .failure, userActivity: nil)
                response.eventTime = "Error fetching events: \(error.localizedDescription)"
                completion(response)
            }
        }
    }
    
    // Handle "when are all the times today" or "all harvester times"
    // Leave commented out for now - we'll add it later after testing
    /*
    func handle(intent: GetAllHarvesterTimesIntent, completion: @escaping (GetAllHarvesterTimesIntentResponse) -> Void) {
        Task {
            let apiService = HarvesterAPIService()
            
            do {
                let allEvents = try await apiService.fetchAllEventsToday()
                
                if allEvents.isEmpty {
                    let response = GetAllHarvesterTimesIntentResponse(code: .failure, userActivity: nil)
                    response.allTimes = "No events scheduled for today"
                    completion(response)
                } else {
                    let timesList = allEvents.map { event in
                        let prefix = event.isCurrent ? "Currently: " : ""
                        return "\(prefix)\(event.startTime) - \(event.endTime) at \(event.maps.joined(separator: ", ")) (\(event.isCurrent ? "Ends in \(event.timeUntil)" : "in \(event.timeUntil)"))"
                    }
                    let response = GetAllHarvesterTimesIntentResponse(code: .success, userActivity: nil)
                    response.allTimes = timesList.joined(separator: ". ")
                    response.count = NSNumber(value: allEvents.count)
                    completion(response)
                }
            } catch {
                let response = GetAllHarvesterTimesIntentResponse(code: .failure, userActivity: nil)
                response.allTimes = "Error fetching events"
                completion(response)
            }
        }
    }
    */
}

